### ISSUE TITLE
New Risk - Insertion of Sensitive Data into Logs

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mastg#2481]
Create a new risk using the following information:
```yaml
alias: data-in-logs
areas:
- Android APIs e.g. Log, Logger, Proguard config, System.out.println, System.err or
  printStackTrace, penaltyLog
- READ_LOGS permission (Android)
- iOS APIs e.g. NSLog, NSAssert, NSCAssert, fprintf, custom functions (Logging, Logfile),
  crash reporters
- macros (if source available)
- Android system logs (dynamic test)
description: Android APIs e.g. Log, Logger or iOS APIs e.g. NSLog, NSAssert.
note: It's privacy because the developer is intentionally writing this data to the
  logs that may become accessible by certain apps (even if the risk is low). Apps
  can only read their own logs on Android 4.1 and higher (unless they are system/preloaded
  apps). On Android 4.0 and lower, apps can read all logs.
platform:
- android
- ios
prev: MSTG-STORAGE-3
profiles:
- L1
- L2
- P
refs:
- https://developer.android.com/topic/security/risks/log-info-disclosure
- https://stackoverflow.com/questions/45270547/is-read-logs-a-normal-or-dangerous-android-permission
relates:
- MASVS-PRIVACY-1
title: Insertion of Sensitive Data into Logs

```
