### ISSUE TITLE
New Risk - Sensitive Data Stored With Insufficient Access Restrictions in Internal Locations

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mastg#2482]
Create a new risk using the following information:
```yaml
alias: data-insufficient-access-restrictions-internal
areas:
- File permissions (Android)
description: not ensuring exclusive app access to sensitive data stored in internal
  locations
platform:
- android
prev: MSTG-STORAGE-2
profiles:
- L1
- L2
refs:
- https://developer.android.com/about/versions/nougat/android-7.0-changes#permfilesys
summary: Inspect internal storage for sensitive data not ensuring exclusive app access
  e.g. by using the wrong file permissions.
title: Sensitive Data Stored With Insufficient Access Restrictions in Internal Locations

```
