### ISSUE TITLE
New Risk - Backup Unencrypted

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mastg#2483]
Create a new risk using the following information:
```yaml
alias: backup-unencrypted
areas:
- Backup Device Conditions clientSideEncryption and deviceToDeviceTransfer Not Checked
  (Android)
description: backup encryption not ensured
platform:
- android
profiles:
- L2
refs:
- https://developer.android.com/guide/topics/data/autobackup#define-device-conditions
title: Backup Unencrypted

```
