### ISSUE TITLE
New Risk - Sensitive Data Not Excluded From Backup

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mastg#2484]
Create a new risk using the following information:
```yaml
alias: data-not-excluded-backup
description: e.g. via `android:fullBackupContent` (Android 11-) or `android:dataExtractionRules`
  (Android 12+) and iOS `isExcludedFromBackup` or file operations that reset backup
  exclusion"
platform:
- android
- ios
prev: MSTG-STORAGE-8
profiles:
- L1
- L2
- P
refs:
- https://developer.android.com/guide/topics/data/autobackup#include-exclude-android-11
- https://developer.android.com/guide/topics/data/autobackup#include-exclude-android-12
relates:
- MASVS-PRIVACY-1
title: Sensitive Data Not Excluded From Backup

```
