### ISSUE TITLE
New Risk - Sensitive Data Hardcoded in the App Package

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mastg#2485]
Create a new risk using the following information:
```yaml
alias: data-hardcoded-app-package
areas:
- app package (APK/IPA)
- app source / compiled binary
- libs
description: sensitive data (including cryptographic and authentication material)
  can be hardcoded in the app package, source code, and compiled binary.
mappings:
- android: https://developer.android.com/privacy-and-security/risks/hardcoded-cryptographic-secrets
- masvs-v2: MASVS-STORAGE-1
platform:
- android
- ios
profiles:
- L1
- L2
summary: Inspect the app package, source code, and compiled binary for hardcoded sensitive
  data.
title: Sensitive Data Hardcoded in the App Package

```
