### ISSUE TITLE
New Risk - Sensitive Data Stored Unencrypted in Internal Locations

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mastg#2486]
Create a new risk using the following information:
```yaml
alias: data-unencrypted-internal
areas:
- envelope encryption (DEK+KEK) or equivalent (Android)
- Android Security Lib usage (EncryptedFile/EncryptedSharedPreferences) (Android)
- Don't roll your own storage encryption, use platform provided APIs EncryptedFile/EncryptedSharedPreferences.
  (Android)
- iOS KeyChain DataProtection classes (iOS)
- envelope encryption (DEK+KEK) or equivalent (iOS)
- sensitive data must not encoded (e.g. base64, simple bit operations such as XOR
  or bit flipping) instead of encrypted
description: not ensuring confidentiality to sensitive data stored in internal locations.
note: encrypting the data will ensure that it's not accessible to other apps or the
  OS itself (via ll possible leakage means e.g. backups)
platform:
- android
- ios
prev: MSTG-STORAGE-14
profiles:
- L2
relates:
- MASVS-CRYPTO-2
summary: Inspect internal storage and internal caches, logs, etc. for unencrypted
  sensitive data.
title: Sensitive Data Stored Unencrypted in Internal Locations

```
