### ISSUE TITLE
New Risk - Sensitive Data Stored Unencrypted in External Locations

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mastg#2487]
Create a new risk using the following information:
```yaml
alias: data-unencrypted-external
areas:
- in scoped storage (external storage, Android)
- in external storage (public folders e.g. SD card, Photos, Downloads, Caches, etc.)
- in external caches
- in app-crafted backups
description: sensitive data can be found in external storage, external caches, and
  in app-crafted backups
platform:
- android
- ios
prev: MSTG-STORAGE-2
profiles:
- L1
- L2
summary: Inspect external storage for unencrypted sensitive data. Inspect the app
  for calls APIs used to store data in public locations (e.g. Downloads folder) and
  make sure that sensitive data is not being stored.
title: Sensitive Data Stored Unencrypted in External Locations

```
