### ISSUE TITLE
New Risk - Device Access Security Policy Not Enforced

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mastg#2488]
Create a new risk using the following information:
```yaml
alias: device-access-policy-not-enforced
areas:
- user set a device passcode via isDeviceSecure() on Android
- LAContext.canEvaluatePolicy() on iOS
description: e.g. user set a device passcode via isDeviceSecure() on Android and LAContext.canEvaluatePolicy()
  on iOS.
platform:
- android
- ios
prev: MSTG-STORAGE-11
profiles:
- L2
relates:
- MASVS-AUTH-2
summary: Inspect the app for calls to device-access-security policy enforcement APIs.
title: Device Access Security Policy Not Enforced

```
