### ISSUE TITLE
New Risk - Weak Cryptographic Key Generation []

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mastg#2489]
Create a new risk using the following information:
```yaml
areas:
- insufficient Key Length
description: e.g. 1024-bit RSA keys, 128-bit AES keys, 160-bit ECDSA keys, 80-bit
  symmetric keys
platform:
- android
- ios
profiles:
- L1
- L2
title: Weak Cryptographic Key Generation

```
