### ISSUE TITLE
New Risk - Weak Cryptographic Key Derivation []

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mastg#2491]
Create a new risk using the following information:
```yaml
areas:
- weak sources
- lack of salt encryption when doing PBKDF2
description: e.g. PBKDF2 with insufficient iterations, lack of salt, etc.
platform:
- android
- ios
profiles:
- L1
- L2
title: Weak Cryptographic Key Derivation

```
