### ISSUE TITLE
New Risk - Cryptographic Key Rotation Not Implemented []

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mastg#2493]
Create a new risk using the following information:
```yaml
description: Key rotation is a best practice to limit the impact of a key compromise.
  It is especially important for long-lived keys such as asymmetric keys.
platform:
- android
- ios
profiles:
- L2
title: Cryptographic Key Rotation Not Implemented

```
