### ISSUE TITLE
New Risk - Cryptographic Key Reuse []

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mastg#2495]
Create a new risk using the following information:
```yaml
description: e.g. using the same key for encryption and signing, using the same key
  for different purposes, etc.
platform:
- android
- ios
prev: MSTG-CRYPTO-5
profiles:
- L2
title: Cryptographic Key Reuse

```
