### ISSUE TITLE
New Risk - Insecure or Wrong Usage of Cryptographic Key []

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mastg#2497]
Create a new risk using the following information:
```yaml
areas:
- authorized key algorithm
- operations or purposes (encrypt, decrypt, sign,...)
description: e.g. using a key for the wrong purpose, using a key with the wrong algorithm,
  etc.
platform:
- android
- ios
profiles:
- L2
title: Insecure or Wrong Usage of Cryptographic Key

```
