### ISSUE TITLE
New Risk - Hardcoded Cryptographic Keys in Use []

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mastg#2499]
Create a new risk using the following information:
```yaml
description: One thing is to include hardcoded keys in the code, another is to use
  them.
platform:
- android
- ios
prev: MSTG-CRYPTO-1
profiles:
- L1
- L2
refs:
- https://developer.android.com/topic/security/risks/hardcoded-cryptographic-secrets
title: Hardcoded Cryptographic Keys in Use

```
