### ISSUE TITLE
New Risk - Cryptographic Keys Not Properly Protected at Rest []

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mastg#2501]
Create a new risk using the following information:
```yaml
areas:
- platform keystore (Android KeyStore / iOS KeyChain)
- TEE/SE
- Cryptographic Keys Not Encrypted with key from platform keystore. envelope encryption
  (DEK+KEK) (considered "equivalent protection")
description: e.g. storing keys in SharedPreferences, storing keys in files, hardcoded
  keys, etc.
platform:
- android
- ios
prev: MSTG-STORAGE-1
profiles:
- L1
- L2
refs:
- NIST.SP.800-175Br1 5.3.5 Key Wrapping
relates:
- MASVS-STORAGE-1
title: Cryptographic Keys Not Properly Protected at Rest

```
