### ISSUE TITLE
New Risk - Deprecated Android KeyStore Implementations []

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mastg#2503]
Create a new risk using the following information:
```yaml
areas:
- Bouncy Castle (BKS)
description: Avoid deprecated implementations such as BKS
platform:
- android
profiles:
- L2
refs:
- https://labs.withsecure.com/publications/how-secure-is-your-android-keystore-authentication
- https://developer.android.com/reference/java/security/KeyStore
- https://developer.android.com/about/versions/12/behavior-changes-all#bouncy-castle
relates:
- MASVS-CODE-3
title: Deprecated Android KeyStore Implementations

```
