### ISSUE TITLE
New Risk - Unsafe Handling of Imported Cryptographic Keys []

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mastg#2505]
Create a new risk using the following information:
```yaml
description: e.g. importing keys from untrusted sources, importing keys from untrusted
  storage, etc.
platform:
- android
- ios
profiles:
- L2
relates:
- MASVS-CODE-4
title: Unsafe Handling of Imported Cryptographic Keys

```
