### ISSUE TITLE
New Risk - Cryptographic Keys Not Properly Protected on Export []

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mastg#2507]
Create a new risk using the following information:
```yaml
description: e.g. use key wrapping even if the key is sent over a secure channel.
platform:
- android
- ios
profiles:
- L2
relates:
- MASVS-STORAGE-1
- MASVS-NETWORK-1
title: Cryptographic Keys Not Properly Protected on Export

```
