### ISSUE TITLE
New Risk - Insertion of Sensitive Data into Logs [data-in-logs]

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mastg#2523]
Create a new risk for "Insertion of Sensitive Data into Logs (MASVS-STORAGE-2)" using the following information:

Android APIs e.g. Log, Logger or iOS APIs e.g. NSLog, NSAssert.

> Note: Should we consider privacy as the primary category since the developer is intentionally writing this data to the logs (a potential data leak is not a side-effect of using the logging APIs) that may become accessible by certain apps (even if the risk is low)? Apps can only read their own logs on Android 4.1 and higher (unless they are system/preloaded apps). On Android 4.0 and lower, apps can read all logs.

Create "`risks/MASVS-STORAGE/2-***-****/data-in-logs/risk.md`" including the following content:

```yaml
---
title: Insertion of Sensitive Data into Logs
alias: data-in-logs
platform: [android, ios]
profiles: [L1, L2, P]
mappings:
- masvs-v1: [MSTG-STORAGE-3]
- masvs-v2: [MASVS-STORAGE-2, MASVS-PRIVACY-1]

---

## Overview

## Impact

## Modes of Introduction

## Mitigations

```

**To complete the sections follow the guidelines from [Writing MASTG Risks & Tests](https://docs.google.com/document/d/1EMsVdfrDBAu0gmjWAUEs60q-fWaOmDB5oecY9d9pOlg/edit?usp=sharing)**

Use at least the following references:

- <https://developer.android.com/topic/security/risks/log-info-disclosure>
- <https://stackoverflow.com/questions/45270547/is-read-logs-a-normal-or-dangerous-android-permission>

When creating the corresponding test, use the following areas to guide you:

- Android APIs e.g. Log, Logger, Proguard config, System.out.println, System.err or printStackTrace, penaltyLog
- READ_LOGS permission (Android)
- iOS APIs e.g. NSLog, NSAssert, NSCAssert, fprintf, custom functions (Logging, Logfile), crash reporters
- macros (if source available)
- Android system logs (dynamic test)

Tip: if the risk has a MASVS v1 ID, you can use it to [search for related tests in the MASTG](https://mas.owasp.org/MASTG/tests/) and use them as input to define your risks and associated tests.
