### ISSUE TITLE
New Risk - Sensitive Data Stored With Insufficient Access Restrictions in Internal Locations [data-insufficient-access-restrictions-internal]

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mastg#2525]
Create a new risk for "Sensitive Data Stored With Insufficient Access Restrictions in Internal Locations (MASVS-STORAGE-2)" using the following information:

Sensitive data may be stored in internal locations without ensuring exclusive app access (e.g. by using the wrong file permissions) and may be accessible to other apps.

Create "`risks/MASVS-STORAGE/2-***-****/data-insufficient-access-restrictions-internal/risk.md`" including the following content:

```yaml
---
title: Sensitive Data Stored With Insufficient Access Restrictions in Internal Locations
alias: data-insufficient-access-restrictions-internal
platform: [android]
profiles: [L1, L2]
mappings:
- masvs-v1: [MSTG-STORAGE-2]
- masvs-v2: [MASVS-STORAGE-2]

---

## Overview

## Impact

## Modes of Introduction

## Mitigations

```

**To complete the sections follow the guidelines from [Writing MASTG Risks & Tests](https://docs.google.com/document/d/1EMsVdfrDBAu0gmjWAUEs60q-fWaOmDB5oecY9d9pOlg/edit?usp=sharing)**

Use at least the following references:

- <https://developer.android.com/about/versions/nougat/android-7.0-changes#permfilesys>

When creating the corresponding test, use the following areas to guide you:

- File permissions (Android)

Tip: if the risk has a MASVS v1 ID, you can use it to [search for related tests in the MASTG](https://mas.owasp.org/MASTG/tests/) and use them as input to define your risks and associated tests.
