### ISSUE TITLE
New Risk - Backup Unencrypted [backup-unencrypted]

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mastg#2527]
Create a new risk for "Backup Unencrypted (MASVS-STORAGE-2)" using the following information:

The app may not encrypt sensitive data in backups, which may compromise data confidentiality.

Create "`risks/MASVS-STORAGE/2-***-****/backup-unencrypted/risk.md`" including the following content:

```yaml
---
title: Backup Unencrypted
alias: backup-unencrypted
platform: [android]
profiles: [L2]
mappings:
- masvs-v1: [MSTG-STORAGE-8]
- masvs-v2: [MASVS-STORAGE-2, MASVS-PRIVACY-1]

---

## Overview

## Impact

## Modes of Introduction

## Mitigations

```

**To complete the sections follow the guidelines from [Writing MASTG Risks & Tests](https://docs.google.com/document/d/1EMsVdfrDBAu0gmjWAUEs60q-fWaOmDB5oecY9d9pOlg/edit?usp=sharing)**

Use at least the following references:

- <https://developer.android.com/guide/topics/data/autobackup#define-device-conditions>

When creating the corresponding test, use the following areas to guide you:

- Backup Device Conditions clientSideEncryption and deviceToDeviceTransfer Not Checked (Android)

Tip: if the risk has a MASVS v1 ID, you can use it to [search for related tests in the MASTG](https://mas.owasp.org/MASTG/tests/) and use them as input to define your risks and associated tests.
