### ISSUE TITLE
New Risk - Sensitive Data Not Excluded From Backup [data-not-excluded-backup]

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mastg#2529]
Create a new risk for "Sensitive Data Not Excluded From Backup (MASVS-STORAGE-2)" using the following information:

sensitive data can be excluded to prevent it from being backed up.

Create "`risks/MASVS-STORAGE/2-***-****/data-not-excluded-backup/risk.md`" including the following content:

```yaml
---
title: Sensitive Data Not Excluded From Backup
alias: data-not-excluded-backup
platform: [android, ios]
profiles: [L1, L2, P]
mappings:
- masvs-v1: [MSTG-STORAGE-8]
- masvs-v2: [MASVS-STORAGE-2, MASVS-PRIVACY-1]

---

## Overview

## Impact

## Modes of Introduction

## Mitigations

```

**To complete the sections follow the guidelines from [Writing MASTG Risks & Tests](https://docs.google.com/document/d/1EMsVdfrDBAu0gmjWAUEs60q-fWaOmDB5oecY9d9pOlg/edit?usp=sharing)**

Use at least the following references:

- <https://developer.android.com/guide/topics/data/autobackup#include-exclude-android-11>
- <https://developer.android.com/guide/topics/data/autobackup#include-exclude-android-12>

When creating the corresponding test, use the following areas to guide you:

- `android:fullBackupContent` (Android 11-) or `android:dataExtractionRules` (Android 12+)
- iOS `isExcludedFromBackup` (iOS)

Tip: if the risk has a MASVS v1 ID, you can use it to [search for related tests in the MASTG](https://mas.owasp.org/MASTG/tests/) and use them as input to define your risks and associated tests.
