### ISSUE TITLE
New Risk - Sensitive Data Stored Unencrypted in External Locations [data-unencrypted-external]

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mastg#2535]
Create a new risk for "Sensitive Data Stored Unencrypted in External Locations (MASVS-STORAGE-1)" using the following information:

Sensitive data may be stored in external locations (e.g. external storage, public folders, etc.) without encryption and may be accessible to other apps.

Create "`risks/MASVS-STORAGE/1-***-****/data-unencrypted-external/risk.md`" including the following content:

```yaml
---
title: Sensitive Data Stored Unencrypted in External Locations
alias: data-unencrypted-external
platform: [android, ios]
profiles: [L1, L2]
mappings:
- masvs-v1: [MSTG-STORAGE-2]
- masvs-v2: [MASVS-STORAGE-1]

---

## Overview

## Impact

## Modes of Introduction

## Mitigations

```

**To complete the sections follow the guidelines from [Writing MASTG Risks & Tests](https://docs.google.com/document/d/1EMsVdfrDBAu0gmjWAUEs60q-fWaOmDB5oecY9d9pOlg/edit?usp=sharing)**

When creating the corresponding test, use the following areas to guide you:

- in scoped storage (external storage, Android)
- in external storage (public folders e.g. SD card, Photos, Downloads, Caches, etc.)
- in external caches
- in app-crafted backups

Tip: if the risk has a MASVS v1 ID, you can use it to [search for related tests in the MASTG](https://mas.owasp.org/MASTG/tests/) and use them as input to define your risks and associated tests.
