### ISSUE TITLE
[MASWE-0004] Sensitive Data Not Excluded From Backup

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mastg#2542]
## Description

Create a new risk for "Sensitive Data Not Excluded From Backup (MASVS-STORAGE-2)" using the following information:

sensitive data can be excluded to prevent it from being backed up.

Create "`risks/MASVS-STORAGE/2-***-****/data-not-excluded-backup/risk.md`" including the following content:

```yaml
---
title: Sensitive Data Not Excluded From Backup
alias: data-not-excluded-backup
platform: [android, ios]
profiles: [L1, L2, P]
mappings:
  masvs-v1: [MSTG-STORAGE-8]
  masvs-v2: [MASVS-STORAGE-2, MASVS-PRIVACY-1]
  mastg-v1: [MASTG-TEST-0058, MASTG-TEST-0009]

---

## Overview

## Impact

## Modes of Introduction

## Mitigations

```

**To complete the sections follow the guidelines from [Writing MASTG Risks & Tests](https://docs.google.com/document/d/1EMsVdfrDBAu0gmjWAUEs60q-fWaOmDB5oecY9d9pOlg/edit?usp=sharing)**

Use at least the following references:

- <https://developer.android.com/guide/topics/data/autobackup#include-exclude-android-11>
- <https://developer.android.com/guide/topics/data/autobackup#include-exclude-android-12>

When creating the corresponding tests, use the following areas to guide you:

- `android:fullBackupContent` (Android 11-) or `android:dataExtractionRules` (Android 12+)
- iOS `isExcludedFromBackup` (iOS)
- cryptographic keys in backups (?)

**MASTG v1 Refactoring:**

If the risk has a MASVS v1 ID, you can use it to [search for related tests in the MASTG](https://mas.owasp.org/MASTG/tests/) and use them as input to define your risks and associated tests.

- [MASTG-TEST-0058 - Testing Backups for Sensitive Data (ios)](https://mas.owasp.org/MASTG/tests/android/MASVS-STORAGE/MASTG-TEST-0058/)
- [MASTG-TEST-0009 - Testing Backups for Sensitive Data (android)](https://mas.owasp.org/MASTG/tests/android/MASVS-STORAGE/MASTG-TEST-0009/)

## Acceptance Criteria

- [ ] The risk has been created in the correct directory (`risks/MASVS-STORAGE/2-***-****/data-not-excluded-backup/risk.md`)
- [ ] The risk content follows the [guidelines](https://docs.google.com/document/d/1EMsVdfrDBAu0gmjWAUEs60q-fWaOmDB5oecY9d9pOlg/edit?usp=sharing)
- [ ] At least one GitHub Issue has been created for the corresponding tests (derived from "Modes of Introduction")
- [ ] The risk indicates the related MASTG v1 tests in its metadata.
