### ISSUE TITLE
New Risk - Sensitive Data Stored Unencrypted in Internal Locations [data-unencrypted-internal]

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mastg#2544]
## Description

Create a new risk for "Sensitive Data Stored Unencrypted in Internal Locations (MASVS-STORAGE-1)" using the following information:

Sensitive data may be stored in internal locations without encryption and may be accessible to other apps under certain conditions.

Create "`risks/MASVS-STORAGE/1-***-****/data-unencrypted-internal/risk.md`" including the following content:

```yaml
---
title: Sensitive Data Stored Unencrypted in Internal Locations
alias: data-unencrypted-internal
platform: [android, ios]
profiles: [L2]
mappings:
- masvs-v1: [MSTG-STORAGE-14]
- masvs-v2: [MASVS-STORAGE-1, MASVS-CRYPTO-2]

---

## Overview

## Impact

## Modes of Introduction

## Mitigations

```

**To complete the sections follow the guidelines from [Writing MASTG Risks & Tests](https://docs.google.com/document/d/1EMsVdfrDBAu0gmjWAUEs60q-fWaOmDB5oecY9d9pOlg/edit?usp=sharing)**

When creating the corresponding test, use the following areas to guide you:

- envelope encryption (DEK+KEK) or equivalent (Android)
- Android Security Lib usage (EncryptedFile/EncryptedSharedPreferences) (Android)
- Don't roll your own storage encryption, use platform provided APIs EncryptedFile/EncryptedSharedPreferences. (Android)
- iOS KeyChain DataProtection classes (iOS)
- envelope encryption (DEK+KEK) or equivalent (iOS)
- sensitive data must not encoded (e.g. base64, simple bit operations such as XOR or bit flipping) instead of encrypted

**MASTG v1 Refactoring:**

If the risk has a MASVS v1 ID, you can use it to [search for related tests in the MASTG](https://mas.owasp.org/MASTG/tests/) and use them as input to define your risks and associated tests.
Include the related MASTG v1 tests in the metadata of the risk. For example:

```yaml
mappings:
- mastg-v1: [MASTG-TEST-11]
```

## Acceptance Criteria

- [ ] The risk has been created in the correct directory (`risks/MASVS-STORAGE/1-***-****/data-unencrypted-internal/risk.md`)
- [ ] The risk content follows the [guidelines](https://docs.google.com/document/d/1EMsVdfrDBAu0gmjWAUEs60q-fWaOmDB5oecY9d9pOlg/edit?usp=sharing)
- [ ] At least one GitHub Issue has been created for the corresponding tests (derived from "Modes of Introduction")
- [ ] The risk indicates the related MASTG v1 tests in its metadata.
