### ISSUE TITLE
New Risk - Device Access Security Policy Not Enforced [device-access-policy-not-enforced]

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mastg#2546]
## Description

Create a new risk for "Device Access Security Policy Not Enforced (MASVS-STORAGE-1)" using the following information:

The app may not enforce device access security policy (e.g. device passcode) and may allow for unauthorized access to sensitive data.

Create "`risks/MASVS-STORAGE/1-***-****/device-access-policy-not-enforced/risk.md`" including the following content:

```yaml
---
title: Device Access Security Policy Not Enforced
alias: device-access-policy-not-enforced
platform: [android, ios]
profiles: [L2]
mappings:
- masvs-v1: [MSTG-STORAGE-11]
- masvs-v2: [MASVS-STORAGE-1, MASVS-AUTH-2]

---

## Overview

## Impact

## Modes of Introduction

## Mitigations

```

**To complete the sections follow the guidelines from [Writing MASTG Risks & Tests](https://docs.google.com/document/d/1EMsVdfrDBAu0gmjWAUEs60q-fWaOmDB5oecY9d9pOlg/edit?usp=sharing)**

When creating the corresponding test, use the following areas to guide you:

- user set a device passcode via isDeviceSecure() on Android
- LAContext.canEvaluatePolicy() on iOS

**MASTG v1 Refactoring:**

If the risk has a MASVS v1 ID, you can use it to [search for related tests in the MASTG](https://mas.owasp.org/MASTG/tests/) and use them as input to define your risks and associated tests.
Include the related MASTG v1 tests in the metadata of the risk. For example:

```yaml
mappings:
- mastg-v1: [MASTG-TEST-11]
```

## Acceptance Criteria

- [ ] The risk has been created in the correct directory (`risks/MASVS-STORAGE/1-***-****/device-access-policy-not-enforced/risk.md`)
- [ ] The risk content follows the [guidelines](https://docs.google.com/document/d/1EMsVdfrDBAu0gmjWAUEs60q-fWaOmDB5oecY9d9pOlg/edit?usp=sharing)
- [ ] At least one GitHub Issue has been created for the corresponding tests (derived from "Modes of Introduction")
- [ ] The risk indicates the related MASTG v1 tests in its metadata.
