### ISSUE TITLE
New Risk - Insecure or Wrong Usage of Cryptographic Key [insecure-key-usage]

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mastg#2576]
## Description

Create a new risk for "Insecure or Wrong Usage of Cryptographic Key (MASVS-CRYPTO-2)" using the following information:

According to NIST.SP.800-57pt1r5, in general, a single key shall be used for only one purpose (e.g., encryption, integrity, authentication, key wrapping, random bit generation, or digital signatures)

Create "`risks/MASVS-CRYPTO/2-***-****/insecure-key-usage/risk.md`" including the following content:

```yaml
---
title: Insecure or Wrong Usage of Cryptographic Key
alias: insecure-key-usage
platform: [android, ios]
profiles: [L2]
mappings:
  masvs-v1: [MSTG-CRYPTO-5]
  masvs-v2: [MASVS-CRYPTO-2]
  mastg-v1: [MASTG-TEST-0062, MASTG-TEST-0015]

---

## Overview

## Impact

## Modes of Introduction

## Mitigations

```

**To complete the sections follow the guidelines from [Writing MASTG Risks & Tests](https://docs.google.com/document/d/1EMsVdfrDBAu0gmjWAUEs60q-fWaOmDB5oecY9d9pOlg/edit?usp=sharing)**

Use at least the following references:

- <https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-57pt1r5.pdf>

When creating the corresponding tests, use the following areas to guide you:

- authorized key algorithm
- key reuse for different purposes or operations (encrypt, decrypt, sign,...)

**MASTG v1 Refactoring:**

If the risk has a MASVS v1 ID, you can use it to [search for related tests in the MASTG](https://mas.owasp.org/MASTG/tests/) and use them as input to define your risks and associated tests.

- [MASTG-TEST-0062 - Testing Key Management (ios)](https://mas.owasp.org/MASTG/tests/android/MASVS-CRYPTO/MASTG-TEST-0062/)
- [MASTG-TEST-0015 - Testing the Purposes of Keys (android)](https://mas.owasp.org/MASTG/tests/android/MASVS-CRYPTO/MASTG-TEST-0015/)

## Acceptance Criteria

- [ ] The risk has been created in the correct directory (`risks/MASVS-CRYPTO/2-***-****/insecure-key-usage/risk.md`)
- [ ] The risk content follows the [guidelines](https://docs.google.com/document/d/1EMsVdfrDBAu0gmjWAUEs60q-fWaOmDB5oecY9d9pOlg/edit?usp=sharing)
- [ ] At least one GitHub Issue has been created for the corresponding tests (derived from "Modes of Introduction")
- [ ] The risk indicates the related MASTG v1 tests in its metadata.
