### ISSUE TITLE
New Risk - Cryptographic Keys Not Properly Protected at Rest [crypto-keys-not-protected-at-rest]

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mastg#2578]
## Description

Create a new risk for "Cryptographic Keys Not Properly Protected at Rest (MASVS-CRYPTO-2)" using the following information:

e.g. storing keys in SharedPreferences, storing keys in files, hardcoded keys, etc.

Create "`risks/MASVS-CRYPTO/2-***-****/crypto-keys-not-protected-at-rest/risk.md`" including the following content:

```yaml
---
title: Cryptographic Keys Not Properly Protected at Rest
alias: crypto-keys-not-protected-at-rest
platform: [android, ios]
profiles: [L1, L2]
mappings:
  masvs-v1: [MSTG-STORAGE-1]
  masvs-v2: [MASVS-CRYPTO-2, MASVS-STORAGE-1]
  mastg-v1: [MASTG-TEST-0052, MASTG-TEST-0001]

---

## Overview

## Impact

## Modes of Introduction

## Mitigations

```

**To complete the sections follow the guidelines from [Writing MASTG Risks & Tests](https://docs.google.com/document/d/1EMsVdfrDBAu0gmjWAUEs60q-fWaOmDB5oecY9d9pOlg/edit?usp=sharing)**

Use at least the following references:

- <https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-57pt1r5.pdf>

When creating the corresponding tests, use the following areas to guide you:

- platform keystore (Android KeyStore / iOS KeyChain)
- TEE/SE
- Cryptographic Keys Not Encrypted with key from platform keystore. envelope encryption (DEK+KEK) (considered "equivalent protection")
- Key Wrapping (NIST.SP.800-175Br1 5.3.5)

**MASTG v1 Refactoring:**

If the risk has a MASVS v1 ID, you can use it to [search for related tests in the MASTG](https://mas.owasp.org/MASTG/tests/) and use them as input to define your risks and associated tests.

- [MASTG-TEST-0052 - Testing Local Data Storage (ios)](https://mas.owasp.org/MASTG/tests/android/MASVS-STORAGE/MASTG-TEST-0052/)
- [MASTG-TEST-0001 - Testing Local Storage for Sensitive Data (android)](https://mas.owasp.org/MASTG/tests/android/MASVS-STORAGE/MASTG-TEST-0001/)

## Acceptance Criteria

- [ ] The risk has been created in the correct directory (`risks/MASVS-CRYPTO/2-***-****/crypto-keys-not-protected-at-rest/risk.md`)
- [ ] The risk content follows the [guidelines](https://docs.google.com/document/d/1EMsVdfrDBAu0gmjWAUEs60q-fWaOmDB5oecY9d9pOlg/edit?usp=sharing)
- [ ] At least one GitHub Issue has been created for the corresponding tests (derived from "Modes of Introduction")
- [ ] The risk indicates the related MASTG v1 tests in its metadata.
