### ISSUE TITLE
New Risk - Unsafe Handling of Imported Cryptographic Keys [unsafe-imported-key-handling]

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mastg#2580]
## Description

Create a new risk for "Unsafe Handling of Imported Cryptographic Keys (MASVS-CRYPTO-2)" using the following information:

Importing keys without validating their origin or integrity, or using insecure custom key exchange protocols, can inadvertently introduce malicious or compromised keys into the app environment.

Create "`risks/MASVS-CRYPTO/2-***-****/unsafe-imported-key-handling/risk.md`" including the following content:

```yaml
---
title: Unsafe Handling of Imported Cryptographic Keys
alias: unsafe-imported-key-handling
platform: [android, ios]
profiles: [L2]
mappings:
  masvs-v2: [MASVS-CRYPTO-2, MASVS-CODE-4]
  mastg-v1: []

---

## Overview

## Impact

## Modes of Introduction

## Mitigations

```

**To complete the sections follow the guidelines from [Writing MASTG Risks & Tests](https://docs.google.com/document/d/1EMsVdfrDBAu0gmjWAUEs60q-fWaOmDB5oecY9d9pOlg/edit?usp=sharing)**

Use at least the following references:

- <https://mas.owasp.org/MASTG/Android/0x05d-Testing-Data-Storage/#secure-key-import-into-keystore>
- <https://developer.android.com/privacy-and-security/keystore#ImportingEncryptedKeys>
- <https://developer.android.com/reference/kotlin/android/security/keystore/KeyProtection>
- <https://developer.apple.com/documentation/security/certificate_key_and_trust_services/keys/storing_keys_as_data#2933724>

When creating the corresponding tests, use the following areas to guide you:

- key import from untrusted sources
- key import from untrusted storage

**MASTG v1 Refactoring:**

If the risk has a MASVS v1 ID, you can use it to [search for related tests in the MASTG](https://mas.owasp.org/MASTG/tests/) and use them as input to define your risks and associated tests.

## Acceptance Criteria

- [ ] The risk has been created in the correct directory (`risks/MASVS-CRYPTO/2-***-****/unsafe-imported-key-handling/risk.md`)
- [ ] The risk content follows the [guidelines](https://docs.google.com/document/d/1EMsVdfrDBAu0gmjWAUEs60q-fWaOmDB5oecY9d9pOlg/edit?usp=sharing)
- [ ] At least one GitHub Issue has been created for the corresponding tests (derived from "Modes of Introduction")
- [ ] The risk indicates the related MASTG v1 tests in its metadata.
