### ISSUE TITLE
New Risk - Improper Verification of Cryptographic Signature [improper-signature-verification]

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mastg#2590]
## Description

Create a new risk for "Improper Verification of Cryptographic Signature (MASVS-CRYPTO-1)" using the following information:

Cryptographic signature verification should be performed properly to ensure the integrity and authenticity of the data.

Create "`risks/MASVS-CRYPTO/1-***-****/improper-signature-verification/risk.md`" including the following content:

```yaml
---
title: Improper Verification of Cryptographic Signature
alias: improper-signature-verification
platform: [android, ios]
profiles: [L1, L2]
mappings:
  masvs-v1: [MSTG-CRYPTO-4]
  masvs-v2: [MASVS-CRYPTO-1]
  mastg-v1: [MASTG-TEST-0014]

---

## Overview

## Impact

## Modes of Introduction

## Mitigations

```

**To complete the sections follow the guidelines from [Writing MASTG Risks & Tests](https://docs.google.com/document/d/1EMsVdfrDBAu0gmjWAUEs60q-fWaOmDB5oecY9d9pOlg/edit?usp=sharing)**

Use at least the following references:

- <https://cwe.mitre.org/data/definitions/347.html>
- <https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.186-5.pdf>

**MASTG v1 Refactoring:**

If the risk has a MASVS v1 ID, you can use it to [search for related tests in the MASTG](https://mas.owasp.org/MASTG/tests/) and use them as input to define your risks and associated tests.

- [MASTG-TEST-0014 - Testing the Configuration of Cryptographic Standard Algorithms (android)](https://mas.owasp.org/MASTG/tests/android/MASVS-CRYPTO/MASTG-TEST-0014/)

## Acceptance Criteria

- [ ] The risk has been created in the correct directory (`risks/MASVS-CRYPTO/1-***-****/improper-signature-verification/risk.md`)
- [ ] The risk content follows the [guidelines](https://docs.google.com/document/d/1EMsVdfrDBAu0gmjWAUEs60q-fWaOmDB5oecY9d9pOlg/edit?usp=sharing)
- [ ] At least one GitHub Issue has been created for the corresponding tests (derived from "Modes of Introduction")
- [ ] The risk indicates the related MASTG v1 tests in its metadata.
