### ISSUE TITLE
New Risk - Insecure Random Usage [insecure-random]

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mastg#2591]
## Description

Create a new risk for "Insecure Random Usage (MASVS-CRYPTO-1)" using the following information:

Using a non-cryptographically secure PRNG in a security context, such as authentication, poses significant risks. An attacker could potentially guess the generated numbers and gain access to privileged data or functionality. Predicting or regenerating random numbers can lead to encryption breaches, compromise sensitive user information, or enable user impersonation.

Create "`risks/MASVS-CRYPTO/1-***-****/insecure-random/risk.md`" including the following content:

```yaml
---
title: Insecure Random Usage
alias: insecure-random
platform: [android, ios]
profiles: [L1, L2]
mappings:
  masvs-v1: [MSTG-CRYPTO-6]
  masvs-v2: [MASVS-CRYPTO-1]
  mastg-v1: [MASTG-TEST-0063, MASTG-TEST-0016]

---

## Overview

## Impact

## Modes of Introduction

## Mitigations

```

**To complete the sections follow the guidelines from [Writing MASTG Risks & Tests](https://docs.google.com/document/d/1EMsVdfrDBAu0gmjWAUEs60q-fWaOmDB5oecY9d9pOlg/edit?usp=sharing)**

Use at least the following references:

- <https://developer.android.com/reference/java/security/SecureRandom>
- <https://developer.android.com/topic/security/risks/weak-prng>
- <https://developer.android.com/privacy-and-security/cryptography#deprecated-functionality>
- <https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-131Ar2.pdf>

**MASTG v1 Refactoring:**

If the risk has a MASVS v1 ID, you can use it to [search for related tests in the MASTG](https://mas.owasp.org/MASTG/tests/) and use them as input to define your risks and associated tests.

- [MASTG-TEST-0063 - Testing Random Number Generation (ios)](https://mas.owasp.org/MASTG/tests/android/MASVS-CRYPTO/MASTG-TEST-0063/)
- [MASTG-TEST-0016 - Testing Random Number Generation (android)](https://mas.owasp.org/MASTG/tests/android/MASVS-CRYPTO/MASTG-TEST-0016/)

## Acceptance Criteria

- [ ] The risk has been created in the correct directory (`risks/MASVS-CRYPTO/1-***-****/insecure-random/risk.md`)
- [ ] The risk content follows the [guidelines](https://docs.google.com/document/d/1EMsVdfrDBAu0gmjWAUEs60q-fWaOmDB5oecY9d9pOlg/edit?usp=sharing)
- [ ] At least one GitHub Issue has been created for the corresponding tests (derived from "Modes of Introduction")
- [ ] The risk indicates the related MASTG v1 tests in its metadata.
