### ISSUE TITLE
Setup the Blog

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mastg#2785]
Setup the blog instead of the current file news.md

https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/ 

Split the news into individual blog pages including the relevant metadata as yaml frontmatter and adding `<!-- more -->` where relevant to indicate the excerpts. 

Include the [.authors.yml](https://squidfunk.github.io/mkdocs-material/plugins/blog/#config.authors_file) file in the blog directory:

```
authors:
  carlos:
    name: Carlos Holguera
    description: Creator
    avatar: https://github.com/OWASP/owasp-mastg/blob/master/docs/assets/carlos.jpg
  sven:
    name: Sven Schleier
    description: Creator
    avatar: https://github.com/OWASP/owasp-mastg/blob/master/docs/assets/sven.jpg
```

assign authors to the all blog post files:
- 2020 and before: sven
- 2021 and after: carlos
